devtools_ignore:
    path: /.well-known/appspecific/com.chrome.devtools.json
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'empty.html.twig'
